### ISSUE TITLE
BSOD on Spec A

### ISSUE THREAD

**Issue by dee-fox** [RedGreenBlue09/WFAv7_Installer#10]
Installation claimed to be successful, logs also show that.
Possibility for client-side errors present: Cyrillic letters used in some path names, Russian version of Windows 10 is used on the deployment machine (making logs unusable).
Device: Nokia Lumia 920 (32 GB, Unlocked, RM-821)

**Comment by RedGreenBlue09** [comment]
What kind of blue screen do you see? The one with big sad face in the middle or the one with QR code? Lastly, can you provide the log file?

**Comment by dee-fox** [comment]
sad smiley emoticon!
logs are barely useable, but i'll try to grab them right now

**Comment by RedGreenBlue09** [comment]
The sad face screen means something is wrong with the BCD file (but I really don't know).

One more question. You used dual-boot or single-boot?

**Comment by dee-fox** [comment]
Singleboot. Can't get the log off the computer I used to deploy, will try again (I don't like using windows on desktop)

**Comment by RedGreenBlue09** [comment]
Okay. I suggest you to also try the dual-boot method when possible as it doesn't make modifications on the partition layout.

**Comment by dee-fox** [comment]
Will do, thanks.

**Comment by dee-fox** [comment]
It still doesn't work, unfortunately, the phone still displays a sad face when booting Windows 10 ARM or bootloops if trying to run Windows Phone (8.1). 20k MB size used.

**Comment by RedGreenBlue09** [comment]
I will investigate that. Thank you for testing it out.

**Comment by RedGreenBlue09** [comment]
Which version of WPinternals did you used to unlock bootloader? Only WPi 2.9 works.

**Comment by RedGreenBlue09** [comment]
Can you try again with WPinternals 2.9 and this [latest](https://github.com/RedGreenBlue09/WFAv7_Installer/archive/refs/heads/master.zip) version?

**Comment by dee-fox** [comment]
> Which version of WPinternals did you used to unlock bootloader? Only WPi 2.9 works.

hmm, haven't thought about that! i used the one i had lying around, which probably is the latest
i'll see through that again later today

**Comment by RedGreenBlue09** [comment]
As of #11, it is confirmed that Spec A installation is working in some cases. Old WPinternals seems to be the culprit.

**Comment by dee-fox** [comment]
Well, that's pretty sucky considering I cannot for the love of me figure out why WPi complains about FFU OS-versions

**Comment by RedGreenBlue09** [comment]
<img width="215" alt="image" src="https://github.com/RedGreenBlue09/WFAv7_Installer/assets/59783856/dce32c92-6476-4dc6-a00f-aee985598508">

If your original FFU version is not there, you will need another donor FFU (yes, both is needed). The donor FFU needs to be anything that it supports. I recommend 950 (XL) FFUs with version 10.0.10586.318.

**Comment by dee-fox** [comment]
Alright. I finally got it.
It works, even though that was quite strange behaviour from something that's supposed to just be file manipulation really
Computers really are magic I guess...

**Comment by RedGreenBlue09** [comment]
See my wiki for more information about Windows 10 ARM on Lumia.  
https://github.com/RedGreenBlue09/WFAv7_Installer/wiki/Apps-on-Windows-10-ARM
