### ISSUE TITLE
Lumia 920 stuck at "Nokia" screen with black background

### ISSUE THREAD

**Issue by jacob1298** [RedGreenBlue09/WFAv7_Installer#11]
I unlocked the bootloader of my Nokia Lumia 920 and flashed the Engineering SLB3 bootloader using WPInternals 2.9. I then went into Mass Storage Mode and followed the instructions on the readme. After the Installer.cmd file completed successfully, I rebooted my Lumia 920 to find it stuck at the "Nokia" screen. What should I do to fix this?

**Comment by jacob1298** [comment]
I got it working after a couple of force reboots and switching in and out of Mass Storage mode.

**Comment by RedGreenBlue09** [comment]
You got it booted with the latest release or the latest commit?

**Comment by jacob1298** [comment]
latest release, but is there a newer windows release?

**Comment by RedGreenBlue09** [comment]
There are no newer Windows builds for ARM(v7) that's as good as 15035. For example the build 16299 is available but it only boots into Windows logo. Keep in mind all Windows 10 ARMv7 builds are LEAKED.

**Comment by RedGreenBlue09** [comment]
Charging is known to not work. We cannot support all features as this is not supported by Microsoft. We can only do our best with existing Windows Phone drivers.

**Comment by jacob1298** [comment]
It charges when it sleeps. Does this use EDK2 or similar? I'd like to look at something like Linux.

**Comment by RedGreenBlue09** [comment]
No. Official Windows Phone firmware is already using EDK2-based UEFI and has built in Windows Boot Manager. WPinternals enables the ability to boot other stuff using the stock firmware. WOA (ARM64) on Lumia 950 uses custom EDK2 though.

For Linux, check mainline4lumia. Spec A devices are not supported though.

**Comment by jacob1298** [comment]
I'll check it out. I actually have a 950 with Windows 11 on it. It's painfully slow though. The 920's lack of ram makes the browser crash, so hopefully Linux won't be as hard on the hardware.

**Comment by jacob1298** [comment]
Just checked, mainline4lumia doesn't support the 920

**Comment by RedGreenBlue09** [comment]
> I'll check it out. I actually have a 950 with Windows 11 on it. It's painfully slow though. The 920's lack of ram makes the browser crash, so hopefully Linux won't be as hard on the hardware.

The browser crashed because you don't have the Andreno display driver installed. You need to get into safe mode to update the display driver.

**Comment by RedGreenBlue09** [comment]
> Just checked, mainline4lumia doesn't support the 920

The only Linux on Lumia project that supports spec A as I know is android4Lumia. No support for 920 though.

**Comment by jacob1298** [comment]
> > I'll check it out. I actually have a 950 with Windows 11 on it. It's painfully slow though. The 920's lack of ram makes the browser crash, so hopefully Linux won't be as hard on the hardware.
> 
> The browser crashed because you don't have the Andreno display driver installed. You need to get into safe mode to update the display driver.

How do I do that?

**Comment by RedGreenBlue09** [comment]
On PC or phone:
```
bcdedit /store <MainOS>:\EFIESP\EFI\Microsoft\Boot\BCD /set {703c511b-98f3-4630-b752-6d177cbfb89c} safeboot minimal
```

Then reboot the phone. After you are in safe mode, open Device Manager and update the basic adapter. You need to select "Pick existing driver on my device" and choose the Andreno driver.

On PC or phone:
```
bcdedit /store <MainOS>:\EFIESP\EFI\Microsoft\Boot\BCD /deletevalue {703c511b-98f3-4630-b752-6d177cbfb89c} safeboot
```

Reboot.

**Comment by jacob1298** [comment]
Thanks. I'll try it

**Comment by jacob1298** [comment]
I tried it, but got the response "The system cannot find the file specified."

**Comment by RedGreenBlue09** [comment]
> I tried it, but got the response "The system cannot find the file specified."

You need to replace <MainOS> with your MainOS drive letter.

**Comment by jacob1298** [comment]
I checked before using the command, and the correct display driver is already installed.

**Comment by RedGreenBlue09** [comment]
The idk. The browser should work when Andreno driver is installed.

**Comment by jacob1298** [comment]
It has only 1gb of ram, and idles at 90% usage

**Comment by RedGreenBlue09** [comment]
Hey, you should check the page file settings. It can be disabled or too small. Increase it to a larger size might fix the issue, runs much slower though.

**Comment by jacob1298** [comment]
Yup, I forgot to say that I messed with the pagefile, which turned out to
be stuck at 0mb by default. It gave me a warning when I first logged on,
and I thought I fixed it, but didn't. After I actually fixed it, it worked
much better, and the browser worked fine.

**Comment by RedGreenBlue09** [comment]
Congrats
