### ISSUE TITLE
Error Lumia 1520 - Global - 937

### ISSUE THREAD

**Issue by qasim185** [RedGreenBlue09/WFAv7_Installer#14]
[04-Sep-23-3.log](https://github.com/RedGreenBlue09/WFAv7_Installer/files/12514675/04-Sep-23-3.log)

Error Log Attach - End on Smily Blue Screen

Driver found 140 installed 0 ( Model Number 3 in Driver Downloader )

**Comment by RedGreenBlue09** [comment]
Is this issue resolved?

**Comment by qasim185** [comment]
Yes this one resolved i will connect with you in Telegram have some small issues
