### ISSUE TITLE
Device not charging

### ISSUE THREAD

**Issue by armX69** [RedGreenBlue09/WFAv7_Installer#16]
When Windows 10 is running, my device doesn't charge and stays on until the battery reaches 0%. Only at that point can I charge it, and the battery charges just enough to restart Windows 10, and then the cycle continues. What can I do? In the wiki, I read about offline charging, but it's only for dual-boot devices (I have Windows in single boot). And one last thing: how do I check how much charge the phone has?

**Comment by RedGreenBlue09** [comment]
Use "Charge threshold" method.

**Comment by armX69** [comment]
Ok solved

**Comment by armX69** [comment]
So then i can turn on my device only when the battery level is higher than the chosen threshold?

**Comment by RedGreenBlue09** [comment]
Yes. Charging does not work on Windows 10 ARM.
