### ISSUE TITLE
Driver Downloader

### ISSUE THREAD

**Issue by ankopriv** [RedGreenBlue09/WFAv7_Installer#19]
Driver downloader does not download drivers for Lumia1520AT&T. When choosing this option only txt file "1520attupsidedown" is being downloaded the components folder is missing. The option for Lumia1520 does download the drivers correctly, however I dont know if this can be used in AT&T version.

**Comment by RedGreenBlue09** [comment]
This is a bug. I'm fixing it.

**Comment by RedGreenBlue09** [comment]
[Driver Downloader.zip](https://github.com/RedGreenBlue09/WFAv7_Installer/files/12702109/Driver.Downloader.zip)
Replace the existing file with this one. This will be released later.

**Comment by RedGreenBlue09** [comment]
> however I dont know if this can be used in AT&T version.
No that doesn't work. Some drivers (even same soc) are device specific which will crash with the wrong phone.

**Comment by RedGreenBlue09** [comment]
New version with this fix released.

**Comment by RedGreenBlue09** [comment]
Is this issue resolved?

**Comment by ankopriv** [comment]
Yes this is resolved the downlaoder works, thank you!
