### ISSUE TITLE
Lumia 640 (dempsey) support.

### ISSUE THREAD

**Issue by jhay06** [RedGreenBlue09/WFAv7_Installer#25]
Can you add the lumia 640 (microsoft-dempsey) rm_1077 ? 
i have unlocked bootloader , but theres no much i can do.

**Comment by RedGreenBlue09** [comment]
640 has no INF driver pack (I'm not the one who make such pack). Furthermore, even with reg method (my installer doesn't supports), it still doesn't have working touch out of box and it requires some manual work to bring it up.

**Comment by jhay06** [comment]
hope someone make it work :) thanks

**Comment by RedGreenBlue09** [comment]
We are trying with our downstream driver pack, but we are unable to find someone with the 640 who are willing to debug it.

**Comment by NimiPvPGamer** [comment]
@RedGreenBlue09 i have a 640 that i could maybe do it
this also exists: https://windowsdev.gitbook.io/lumia-woa32/wstep

**Comment by RedGreenBlue09** [comment]
Hi @NimiPvPGamer. Thank you for your attention. You may join the Telegram group and I will provide instructions there.

Sorry for the slow response.

**Comment by jhayar0719** [comment]
> @RedGreenBlue09 i have a 640 that i could maybe do it this also exists: https://windowsdev.gitbook.io/lumia-woa32/wstep

hope that you can make it

**Comment by RedGreenBlue09** [comment]
It is now supported! Try the latest version.

**Comment by jhay06** [comment]
wow its been a while then i saw it is now supported will try it thanka
