### ISSUE TITLE
:( Blue screen lumia 520 after installation

### ISSUE THREAD

**Issue by portalwww** [RedGreenBlue09/WFAv7_Installer#29]
![17045742874186021136090439345512](https://github.com/RedGreenBlue09/WFAv7_Installer/assets/121117755/912d4797-0886-4742-a702-d7f9ccf6fe39)

**Comment by RedGreenBlue09** [comment]
Please unlock with WPinternal 2.9 or newer.

**Comment by portalwww** [comment]
> Please unlock with WPinternal 2.9 or newer.

oh thanks after installation my phone frizze
on loading screen

**Comment by RedGreenBlue09** [comment]
Yep thats a issue on 520. Unfortunately i dont have any idea why.
