### ISSUE TITLE
After instaling win 10 arm on my lumia 930 with 14393.1066 bluescreens

### ISSUE THREAD

**Issue by Intelinsidecom** [RedGreenBlue09/WFAv7_Installer#30]

**Comment by RedGreenBlue09** [comment]
The blue screen has QR code or sad face? Can you send me logs?

**Comment by Intelinsidecom** [comment]
Sad face

**Comment by Intelinsidecom** [comment]
#### INSTALLATION WAS STARTED AT 14:12:06.56 #### 
========================================================= 
## Device is 1  ## 
## MainOS is L: ## 
 
## MainOS DriveLetter is L: ## 
## DPP PN is 1 ## 
## EFIESP PN is 25 ## 
## Data PN is 28 ## 
## Dualboot is y ## 
## Win10SizeMB is 16000 ## 
The type of the file system is NTFS.
Volume label is Data.

Stage 1: Examining basic file system structure ...
Progress: 0 of 3584 done; Stage:  0%; Total:  0%; ETA:   0:00:12    
Progress: 3584 of 3584 done; Stage: 100%; Total: 28%; ETA:   0:00:09 .  
                                                                                       
                                                                                       
  3584 file records processed.                                                        

File verification completed.
 Phase duration (File record verification): 260.94 milliseconds.
Progress: 1 of 1 done; Stage: 100%; Total: 13%; ETA:   0:00:10 .. 
                                                                                       
                                                                                       
  1 large file records processed.                                   

 Phase duration (Orphan file record recovery): 0.00 milliseconds.
Progress: 0 of 0 done; Stage: 99%; Total: 13%; ETA:   0:00:11 ...
                                                                                       
                                                                                       
  0 bad file records processed.                                     

 Phase duration (Bad file record checking): 0.12 milliseconds.

Stage 2: Examining file name linkage ...
Progress: 3587 of 9412 done; Stage: 38%; Total: 29%; ETA:   0:00:19    
Progress: 1 of 1 done; Stage: 100%; Total: 29%; ETA:   0:00:19 .  
                                                                                       
                                                                                       
  1 reparse records processed.                                      

Progress: 9412 of 9412 done; Stage: 100%; Total: 46%; ETA:   0:00:14 .. 
                                                                                       
                                                                                       
  9412 index entries processed.                                                       

Index verification completed.
 Phase duration (Index verification): 568.36 milliseconds.
Progress: 0 of 0 done; Stage: 99%; Total: 46%; ETA:   0:00:14 ...
                                                                                       
                                                                                       
  0 unindexed files scanned.                                        

 Phase duration (Orphan reconnection): 2.47 milliseconds.
Progress: 0 of 0 done; Stage: 99%; Total: 46%; ETA:   0:00:14    
                                                                                       
                                                                                       
  0 unindexed files recovered to lost and found.                    

 Phase duration (Orphan recovery to lost and found): 2.68 milliseconds.
Progress: 1 of 1 done; Stage: 100%; Total: 46%; ETA:   0:00:14 .  
                                                                                       
                                                                                       
  1 reparse records processed.                                      

 Phase duration (Reparse point and Object ID verification): 0.64 milliseconds.

Stage 3: Examining security descriptors ...
Security descriptor verification completed.
 Phase duration (Security descriptor verification): 134.34 milliseconds.
Progress: 0 of 0 done; Stage: 100%; Total: 99%; ETA:   0:00:00 .. 
                                                                                       
                                                                                       
  2915 data files processed.                                           

 Phase duration (Data attribute verification): 0.32 milliseconds.
CHKDSK is verifying Usn Journal...
Progress: 142 of 142 done; Stage: 100%; Total: 71%; ETA:   0:00:00 ...
                                                                                       
                                                                                       
  1169800 USN bytes processed.                                                           

Usn Journal verification completed.
 Phase duration (USN journal verification): 46.47 milliseconds.

Windows has scanned the file system and found no problems.
No further action is required.

  27979759 KB total disk space.
    214768 KB in 544 files.
      3088 KB in 2916 indexes.
         0 KB in bad sectors.
     59887 KB in use by the system.
     52176 KB occupied by the log file.
  27702016 KB available on disk.

     16384 bytes in each allocation unit.
   1748734 total allocation units on disk.
   1731376 allocation units available on disk.
Total duration: 1.72 seconds (1723 ms).
The type of the file system is NTFS.
Volume dismounted.  All opened handles to this volume are now invalid.
Volume label is MainOS.

Stage 1: Examining basic file system structure ...
Progress: 0 of 16640 done; Stage:  0%; Total:  0%; ETA:   0:00:49    
Progress: 3329 of 16640 done; Stage: 20%; Total:  6%; ETA:   0:00:47 .  
Progress: 10753 of 16640 done; Stage: 64%; Total: 21%; ETA:   0:00:39 .. 
Progress: 16640 of 16640 done; Stage: 100%; Total: 32%; ETA:   0:00:03 ...
                                                                                       
                                                                                       
  16640 file records processed.                                                        

File verification completed.
 Phase duration (File record verification): 1.10 seconds.
Progress: 1 of 1 done; Stage: 100%; Total: 28%; ETA:   0:00:03    
                                                                                       
                                                                                       
  1 large file records processed.                                   

 Phase duration (Orphan file record recovery): 0.00 milliseconds.
Progress: 0 of 0 done; Stage: 99%; Total: 28%; ETA:   0:00:03 .  
                                                                                       
                                                                                       
  0 bad file records processed.                                     

 Phase duration (Bad file record checking): 0.20 milliseconds.

Stage 2: Examining file name linkage ...
Progress: 11939 of 21648 done; Stage: 55%; Total: 48%; ETA:   0:00:01 .. 
Progress: 5 of 5 done; Stage: 100%; Total: 57%; ETA:   0:00:01 ...
                                                                                       
                                                                                       
  5 reparse records processed.                                      

Progress: 16854 of 21648 done; Stage: 77%; Total: 61%; ETA:   0:00:01    
Progress: 17482 of 21648 done; Stage: 80%; Total: 63%; ETA:   0:00:01 .  
Progress: 18983 of 21648 done; Stage: 87%; Total: 67%; ETA:   0:00:01 .. 
Progress: 19024 of 21648 done; Stage: 87%; Total: 71%; ETA:   0:00:01 ...
Progress: 19060 of 21648 done; Stage: 88%; Total: 76%; ETA:   0:00:01    
Progress: 21648 of 21648 done; Stage: 100%; Total: 76%; ETA:   0:00:01 .  
                                                                                       
                                                                                       
  21648 index entries processed.                                                       

Index verification completed.
 Phase duration (Index verification): 2.77 seconds.
CHKDSK is scanning unindexed files for reconnect to their original directory.
Progress: 1 of 1 done; Stage: 100%; Total: 76%; ETA:   0:00:01 .. 
                                                                                       
                                                                                       
  1 unindexed files scanned.                                        

  0 unindexed files recovered to original directory.
 Phase duration (Orphan reconnection): 0.00 milliseconds.
CHKDSK is recovering remaining unindexed files.
Progress: 1 of 1 done; Stage: 100%; Total:  0%; ETA: 999:00:00 ...
                                                                                       
                                                                                       
  1 unindexed files recovered to lost and found.                    

    Lost and found is located at \found.000

 Phase duration (Orphan recovery to lost and found): 0.00 milliseconds.
Progress: 5 of 5 done; Stage: 100%; Total:  0%; ETA: 999:00:00    
                                                                                       
                                                                                       
  5 reparse records processed.                                      

 Phase duration (Reparse point and Object ID verification): 0.58 milliseconds.

Stage 3: Examining security descriptors ...
Security descriptor verification completed.
 Phase duration (Security descriptor verification): 116.84 milliseconds.
Progress: 0 of 0 done; Stage: 100%; Total: 99%; ETA:   0:00:00 .  
                                                                                       
                                                                                       
  2505 data files processed.                                           

 Phase duration (Data attribute verification): 0.26 milliseconds.
CHKDSK is verifying Usn Journal...
Usn Journal verification completed.
Correcting errors in the master file table's (MFT) BITMAP attribute.

Windows has made corrections to the file system.
No further action is required.

   2424415 KB total disk space.
   1764432 KB in 13940 files.
      5936 KB in 2507 indexes.
         0 KB in bad sectors.
     31855 KB in use by the system.
     14176 KB occupied by the log file.
    622192 KB available on disk.

     16384 bytes in each allocation unit.
    151525 total allocation units on disk.
     38887 allocation units available on disk.
Total duration: 4.27 seconds (4277 ms).
Insufficient disk space for CHKDSK to recover lost files.
## Resize-Partition ## 
## New-Partition ## 
## Windows 10 drive is L:\Windows10 ## 
The type of the file system is NTFS.
QuickFormatting 15.6 GB
Creating file system structures.
Format complete.                         
      15.6 GB total disk space.
      15.6 GB are available.
========================================================= 

Deployment Image Servicing and Management tool
Version: 10.0.19041.1

Applying image

[                           1.0%                           ] 

[=                          2.0%                           ] 

[=                          3.0%                           ] 

[==                         4.0%                           ] 

[==                         5.0%                           ] 

[===                        6.0%                           ] 

[====                       7.0%                           ] 

[====                       8.0%                           ] 

[=====                      9.0%                           ] 

[=====                      10.0%                          ] 

[======                     11.0%                          ] 

[======                     12.0%                          ] 

[=======                    13.0%                          ] 

[========                   14.0%                          ] 

[========                   15.0%                          ] 

[=========                  16.0%                          ] 

[=========                  17.0%                          ] 

[==========                 18.0%                          ] 

[===========                19.0%                          ] 

[===========                20.0%                          ] 

[============               21.0%                          ] 

[============               22.0%                          ] 

[=============              23.0%                          ] 

[=============              24.0%                          ] 

[==============             25.0%                          ] 

[===============            26.0%                          ] 

[===============            27.0%                          ] 

[================           28.0%                          ] 

[================           29.0%                          ] 

[=================          30.0%                          ] 

[=================          31.0%                          ] 

[==================         32.0%                          ] 

[===================        33.0%                          ] 

[===================        34.0%                          ] 

[====================       35.0%                          ] 

[====================       36.0%                          ] 

[=====================      37.0%                          ] 

[======================     38.0%                          ] 

[======================     39.0%                          ] 

[=======================    40.0%                          ] 

[=======================    41.0%                          ] 

[========================   42.0%                          ] 

[========================   43.0%                          ] 

[=========================  44.0%                          ] 

[========================== 45.0%                          ] 

[========================== 46.0%                          ] 

[===========================47.0%                          ] 

[===========================48.0%                          ] 

[===========================49.0%                          ] 

[===========================50.0%                          ] 

[===========================51.0%                          ] 

[===========================52.0%                          ] 

[===========================53.0%                          ] 

[===========================54.0%                          ]

**Comment by RedGreenBlue09** [comment]
Pls drag the file instead of the text.
