### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by WalkTheEarth** [RedGreenBlue09/WFAv7_Installer#49]
Hi all, 

Im running tiny10 on my main laptop. everytime i have to run ` for /f %%i in ('Powershell -C "(Get-Partition | ? { $_.AccessPaths -eq ''%MainOS%\Data\'' }).PartitionNumber 2>$null"') do set "PartitionNumberData=%%i"` it doesnt work. (empty PartitionNumberData)
any help?

**Comment by RedGreenBlue09** [comment]
It only work if you properly set up the Data mount point in MainOS like default. Maybe send me the screenshot of the mount point?

**Comment by WalkTheEarth** [comment]
It has not been detected manually, but I have set it to E:

**Comment by RedGreenBlue09** [comment]
I mean the Data folder in MainOS

**Comment by WalkTheEarth** [comment]
E:/Data

**Comment by RedGreenBlue09** [comment]
Give me the screenshot of it in file explorer

**Comment by WalkTheEarth** [comment]
![explorer_PjCbX1EoIc](https://github.com/user-attachments/assets/11fbb1db-3f87-4a16-b0fc-aed1d8a15d54)

**Comment by WalkTheEarth** [comment]
this is E:\

**Comment by RedGreenBlue09** [comment]
I don't see EFIESP abd DPP mounted. Seems like you have an unusual MainOS layout. Try flash original FFU and try again. Also use the latest installer from Releases page, don't use development versions.

**Comment by WalkTheEarth** [comment]
1. I already have flashed FFU
2. I do have stable too.

**Comment by WalkTheEarth** [comment]
i was debugging bc it wasnt working

**Comment by RedGreenBlue09** [comment]
Please send the full log.

**Comment by WalkTheEarth** [comment]
when i find my 640, wherever i put it qwq

**Comment by WalkTheEarth** [comment]
SOLVED
i had to mount all partitions first then run wfa
