### ISSUE TITLE
Lumia 1520 Mirrored Touch [FIXED]

### ISSUE THREAD

**Issue by LanderClaes** [RedGreenBlue09/WFAv7_Installer#52]
I tried it out on the lumia 1520, and the touchscreen is mirrored/inverted, when i touch the upper screen it touches down, and same thing for left and right, could you guys fix it or send/release a fixed driver?

**Comment by RedGreenBlue09** [comment]
You can try the fix here: https://github.com/RedGreenBlue09/WFAv7_Installer/wiki/Boot-and-setup-Windows-10-ARM

**Comment by LanderClaes** [comment]
It works! Cant believe i missed that page xD, thanks!
